### PR TITLE
feat(module/vpc_route): Refactor `vpc_route` module - move and simplify locals

### LINKED ISSUE #70: Refactor `vpc_route` module - move and simplify locals

### PR DESCRIPTION
**Pull request by sebastianczech**
## Description

Resolves #70 

## Motivation and Context

#53 

## How Has This Been Tested?

Code was tested locally and via ChatOps.

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sebastianczech** [comment]
/plan paths="examples/centralized_design examples/centralized_design_autoscale examples/combined_design examples/combined_design_autoscale examples/isolated_design examples/isolated_design_autoscale examples/panorama_standalone examples/vmseries_standalone examples/cloudngfw_combined_design examples/cloudngfw_isolated_design"

**Comment by sebastianczech** [comment]
/plan paths="examples/centralized_design examples/centralized_design_autoscale examples/combined_design examples/combined_design_autoscale examples/isolated_design examples/isolated_design_autoscale examples/panorama_standalone examples/vmseries_standalone examples/cloudngfw_combined_design examples/cloudngfw_isolated_design"

**Review by michalbil — APPROVED** [review]

**Comment by sebastianczech** [comment]
As I'm not a part of Palo Alto Networks organisation anymore, I cannot merge changes from `rc` branch into `refactor_vpc_route` branch to resolve conflicts in this branch. Can somebody from repository owners do it or should I create fork of that repository and open new PR with resolved conflicts ?

**Comment by sebastianczech** [comment]
I resolved conflicts by forking repository and opening new PR https://github.com/PaloAltoNetworks/terraform-aws-swfw-modules/pull/79. If you agree on changes in #79, please close this PR without mering.

**Pull request closed without merging**
