### PR TITLE
feat: Cloudngfw Combined Design Model

### PR DESCRIPTION
**Pull request by lstadnik**
## Description

The CloudNGFW example with appropriate module was introduced in this PR. This is the first reference architecture published and it is related to our roadmap - Issue #9 

Motivation and Context
Easy to use module should support all referenced architecture related with CloudNGFW.

How Has This Been Tested?
On dev environment the traffic was inspected against simple any - any and any -deny rule.

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by sebastianczech — APPROVED** [review]

**Comment by migara** [comment]
@seanyoungberg can you please review the architecture here? Should we recommend having a single Cloud NGFW resource for both inbound and outbound/eastwest traffic?

**Comment by seanyoungberg** [comment]
Sure let me try to execute this to get better feel for what the build looks like

**Pull request merged**
