### PR TITLE
ci: Introduce Terraform 1.6 and 1.7 in CI workflows, fix README and update test skeleton version

### PR DESCRIPTION
**Pull request by sebastianczech**
## Description

PR delivers multiple improvements:
- Terraform 1.6 and 1.7 is added in CI workflows
- problem with white characters in README is fixed
- version of `terraform-modules-swfw-tests-skeleton` is updated

## Motivation and Context

- Since this version of Terraform is officially supported by the modules, test should be run using this version.
- With white characters there were issues with `pre-commit` (please check failed first `/sca` ChatOps command).
- There were errors while executing tests (please check failed first `/plan` ChatOps command), so version of `terraform-modules-swfw-tests-skeleton` was increased (after renaming package from `terraform-modules-vmseries-tests-skeleton`)

## How Has This Been Tested?

Changes was tested using ChatOps. Please check PR comments.

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sebastianczech** [comment]
/plan paths="examples/centralized_design examples/centralized_design_autoscale examples/combined_design examples/combined_design_autoscale examples/isolated_design examples/isolated_design_autoscale examples/panorama_standalone examples/vmseries_standalone" tf_version="1.7"

**Comment by sebastianczech** [comment]
/plan paths="examples/centralized_design examples/centralized_design_autoscale examples/combined_design examples/combined_design_autoscale examples/isolated_design examples/isolated_design_autoscale examples/panorama_standalone examples/vmseries_standalone" tf_version="1.7"

**Comment by sebastianczech** [comment]
/idempotence paths="examples/centralized_design examples/centralized_design_autoscale examples/combined_design examples/combined_design_autoscale examples/isolated_design examples/isolated_design_autoscale examples/panorama_standalone examples/vmseries_standalone" tf_version="1.7"

**Comment by sebastianczech** [comment]
/plan paths="examples/centralized_design examples/centralized_design_autoscale examples/combined_design examples/combined_design_autoscale examples/isolated_design examples/isolated_design_autoscale examples/panorama_standalone examples/vmseries_standalone" tf_version="1.6"

**Review by pimielowski — APPROVED** [review]
Good job! 👍

**Review by michalbil — APPROVED** [review]

**Pull request merged**
